$users = [{
  name: "Claudia Lawrence",
  email: "claudialawrence@nf.sympatico.ca",
  subscription_type: "3-Month Digital",
  Start_date: "2021-03-29",
  expiry_date: "2021/06/29",
}, {
  name: "taralsheppard@gmail.com",
  email: "taralsheppard@gmail.com",
  subscription_type: "6 Month Digital",
  Start_date: "2021-03-29",
  expiry_date: "2021/09/29",
},
         {
  name: "Marilyn Hayes",
  email: "m.hayes@sympatico.ca",
  subscription_type: "6 Month Digital",
  Start_date: "2021/02/27",
  expiry_date: "2021/05/27",
}, {
  name: "elaine.devereaux@nf.sympatico.ca",
  email: "elaine.devereaux@nf.sympatico.ca",
  subscription_type: "3 Month Digital",
  start_date: "2021/02/27",
  expiry_date: "2021/05/27",
}, {
  name: "Melissa Samms",
  email: "melissa.samms@gmail.com",
  subscription_type: "3 Month Digi",
  start_date: "2021/02/22",
  expiry_date: "2021/05/22",
}, {
  name: "Keith Bowes",
  email: "kbowes@matadormining.com.au",
  subscription_type: "3 Month Digital",
  start_date: "2021/02/22",
  expiry_date: "2021/05/22",
}, {
  name: "charmaine.pope@eastlink.ca",
  email: "charmaine.pope@eastlink.ca",
  subscription_type: "6",
  start_date: "2021/02/03",
  expiry_date: "2021/08/03",
}, {
  name: "Shane Snook",
  email: "ss.wanderingwhitewolf@gmail.com",
  subscription_type: "3-Month Digital",
  start_date: "2021/02/02",
  expiry_date: "2021/05/02",
}, {
  name: "gffcook@gmail.com",
  email: "gffcook@gmail.com",
  subscription_type: "6 Month digi",
  start_date: "2021/01/27",
  expiry_date: "2021/07/28",
}, {
  name: "glendahatcherrn@hotmail.com",
  email: "glendahatcherrn@hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2021/01/25",
  expiry_date: "2021/04/25",
}, {
  name: "Diane Francis-Gosse",
  email: "dianemgosse@gmail.com",
  subscription_type: "Annual Digital $60",
  start_date: "2021/01/25",
  expiry_date: "annual",
}, {
  name: "travis_cormier@hotmail.com",
  email: "travis_cormier@hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2021/01/17",
  expiry_date: "2021/04/17",
}, {
  name: "Roy Jahchan",
  email: "royjahchan@gmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2021/01/11",
  expiry_date: "2021/04/11",
}, {
  name: "Lori Bennett",
  email: "lori.bennett@rogers.com",
  subscription_type: "Annual Digital $60",
  start_date: "2021/01/06",
  expiry_date: "annual",
}, {
  name: "John Wright",
  email: "potteryjohn@gmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/12/05",
  expiry_date: "annual",
}, {
  name: "moosebateman@hotmail.com",
  email: "moosebateman@hotmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/11/30",
  expiry_date: "annual",
}, {
  name: "Bruce Livingston",
  email: "stevestonecotours@gmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/11/17",
  expiry_date: "annual",
}, {
  name: "Tara Laing",
  email: "tlaing@marine-atlantic.ca",
  subscription_type: "Annual Digital 60",
  start_date: "2021/11/16",
  expiry_date: "annual",
}, {
  name: "Thelma Dominey",
  email: "tdominey@wreckhousepress.com",
  subscription_type: "Annual Digital 60",
  start_date: "2021-11-16",
  expiry_date: "annual",
}, {
  name: "larrypeckford@gmail.com",
  email: "larrypeckford@gmail.com",
  subscription_type: "Annual Digital 60",
  start_date: "2021-11-15",
  expiry_date: "annual",
}, {
  name: "Cabot Martin",
  email: "cabotjwm@gmail.com",
  subscription_type: "6 Month Digital",
  start_date: "2020-10-14",
  expiry_date: "2021/04/14",
}, {
  name: "",
  email: "donnaelms@hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2020/09/16",
  expiry_date: "2020/12/16",
}, {
  name: "staynfld@gmail.com",
  email: "staynfld@gmail.com",
  subscription_type: "Annual Digital 60",
  start_date: "2020/09/16",
  expiry_date: "annual",
}, {
  name: "Andrew Parsons",
  email: "andrewparsons@gov.nl.ca",
  subscription_type: "Annual Digital 60",
  start_date: "2021/09/14",
  expiry_date: "annual",
}, {
  name: "shawn.lillington@bellaliant.net",
  email: "shawn.lillington@bellaliant.net",
  subscription_type: "Annual Digital 60",
  start_date: "2021/09/02",
  expiry_date: "annual",
}, {
      name: "tskinner2002@hotmail.com",
      email: "tskinner2002@hotmail.com",
      subscription_type: "Annual Digital 60",
      start_date: "2021-08-31",
      expiry_date: "annual",
    }, {
        name: "Rosalyn Roy",
        email: "tygerlylly448@hotmail.com",
        subscription_type: "Annual Digital 60",
        start_date: "2021-08-31",
        expiry_date: "annual",
      }, {
          name: "Darlene Kettle",
          email: "darlenekettle@eastlink.ca",
          subscription_type: "Annual Digital 60",
          start_date: "2021-08-29",
          expiry_date: "annual",
        }, {
            name: "Niki Carroll",
            email: "starchild698@yahoo.ca",
            subscription_type: "Annual Digital 60",
            start_date: "2021-08-27",
            expiry_date: "annual",
          }, {
  name: "twosmond@gmail.com",
  email: "twosmond@gmail.com",
  subscription_type: "Annual Digital 60",
  start_date: "2021-08-26",
  expiry_date: "annual",
},
  {
              name: "madjack7691@gmail.com",
              email: "madjack7691@gmail.com",
              subscription_type: "",
              start_date: "",
              expiry_date: "02/02/2019",
            },
  {
    name: "sandrabillard2@gmail.com",
    email: "sandrabillard2@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "drugplay@gmail.com",
    email: "drugplay@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "rosaliejillett@nf.sympatico.ca",
    email: "rosaliejillett@nf.sympatico.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: "",
  }, {
    name: "enos.skeard@gmail.com",
    email: "enos.skeard@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: "02/02/2019",
  }, {
    name: "danny.thomas@hotmail.com",
    email: "danny.thomas@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "nikicarroll@nlesd.ca",
    email: "nikicarroll@nlesd.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "vic.h.cole@gmail.com",
    email: "vic.h.cole@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "keeping_19@hotmail.com",
    email: "keeping_19@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "tracyenwood@hotmail.com",
    email: "tracyenwood@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "loribillard@nlesd.ca",
    email: "loribillard@nlesd.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "info.intervale@gmail.com",
    email: "info.intervale@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "tracyenwood@hotmail.com",
    email: "tracyenwood@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "sjfrancis585@gmail.com",
    email: "sjfrancis585 @gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "kerribond63@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "rmdunphy@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "jane.sheaves@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "kblanchard@intervale.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "ruadhcaileag@yahoo.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "lisagaglione@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "josh_13leaf@yahoo.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "lloydblundon@rogers.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "burntislands1975@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "sytd8xfsd7@privaterelay.appleid.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "brenpope@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "josh@jwalteraqualityservices.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "c.w.bennett@icloud.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "semjones2002@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "lisamadina@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "jody.lomond@live.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "trinamunden@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "supernewfi27@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "d-leriche@hotmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "charleneblackmore@yahoo.ca",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "kylemcoughlindev@gmail.com",
    subscription_type: "",
    start_date: "",
    expiry_date: nil,
  }, {
    name: "",
    email: "rroy@wreckhousepress.com",
    subscription_type: "",
    start_date: "",
    expiry_date: 'annual',
  }, {
    name: "",
    email: "rjroy@wreckhousepress.com",
    subscription_type: "",
    start_date: "",
    expiry_date: 'annual',
  }
]


# def get_users
# $users
# end



puts $users.length
