users = [{
  name: "Marilyn Hayes",
  email: "m.hayes@sympatico.ca",
  subscription_type: "6 Month Digital",
  Start_date: "2021/02/27",
  expiry_date: "2021/05/27",
},{
  name: "elaine.devereaux@nf.sympatico.ca",
  email: "elaine.devereaux @nf.sympatico.ca",
  subscription_type: "3 Month Digital",
  start_date: "2021/02/27",
  expiry_date: "2021/05/27",
},{
  name: "Melissa Samms",
  email: "melissa.samms@gmail.com",
  subscription_type: "3 Month Digi",
  start_date: "2021/02/22",
  expiry_date: "2021/05/22",
},{
  name: "Keith Bowes",
  email: "kbowes@matadormining.com.au",
  subscription_type: "3 Month Digital",
  start_date: "2021/02-22",
  expiry_date: "2021/05/22",
},{
  name: "charmaine.pope@eastlink.ca",
  email: "charmaine.pope@eastlink.ca",
  subscription_type: "6",
  start_date: "2021-02-03",
  expiry_date: "2021/08/03",
},{
  name: "Shane Snook",
  email: "ss.wanderingwhitewolf@gmail.com",
  subscription_type: "3-Month Digital",
  start_date: "2021-02-02",
  expiry_date: "2021/05/02",
},{
  name: "gffcook@gmail.com",
  email: "gffcook@gmail.com",
  subscription_type: "6 Month digi",
 start_date: "2021-01-27",
  expiry_date: "2021/07/28",
},{
  name: "glendahatcherrn@hotmail.com",
  email: "glendahatcherrn@hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2021-01-25",
  expiry_date: "2021/04/25",
},{
  name: "Diane Francis-Gosse",
  email: "dianemgosse@gmail.com",
  subscription_type: "Annual Digital $60",
  start_date: "2021-01-25",
  expiry_date: 'annual',
},{
  name: "travis_cormier@hotmail.com",
  email: "travis_cormier @hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2021-01-17",
  expiry_date: "2021/04/17",
},{
  name: "Roy Jahchan",
  email: "royjahchan@gmail.com",
 subscription_type: "3 Month Digital",
  start_date: "2021-01-11",
  expiry_date: "2021/04/11",
},{
  name: "Lori Bennett",
  email: "lori.bennett@rogers.com",
  subscription_type: "Annual Digital $60",
  start_date: "2021/01/06",
  expiry_date: nil,
},{
  name: "John Wright",
  email: "potteryjohn@gmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/12/05",
  expiry_date: nil,
},{
  name: "moosebateman@hotmail.com",
  email: "moosebateman@hotmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/11/30",
  expiry_date: nil,
},{
  name: "Bruce Livingston",
  email: "stevestonecotours@gmail.com",
  subscription_type: "Annual digital 60",
  start_date: "2020/11/17",
  expiry_date: nil,
},{
  name: "Tara Laing",
  email: "tlaing@marine-atlantic.ca",
  subscription_type: "Annual Digital 60",
  start_date: "2021/11/16",
  expiry_date: nil,
  },{
  name: "Thelma Dominey",
  email: "tdominey@wreckhousepress.com",
  subscription_type: "Annual Digital 60",
  start_date: "2021-11-16",
  expiry_date: nil,
},{
  name: "larrypeckford@gmail.com",
  email: "larrypeckford@gmail.com",
  subscription_type: "Annual Digital 60",
  start_date: "2021-11-15",
  expiry_date: nil,
},{
  name: "Cabot Martin",
  email: "cabotjwm@gmail.com",
  subscription_type: "6 Month Digital",
  start_date: "2020-10-14",
  expiry_date: "2021-04-14"
},{
  name: "Claudia Lawrence",
  email: "claudialawrence@nf.sympatico.ca",
  subscription_type: "6 Month Digital",
  start_date: "2020-09-29",
  expiry_date: "2021-03-29",
},{
  name: "",
  email: "donnaelms@hotmail.com",
  subscription_type: "3 Month Digital",
  start_date: "2020-09-16",
  expiry_date: "2020-12-16",
},{
  name: "staynfld@gmail.com",
  email: "staynfld@gmail.com",
 subscription_type: "Annual Digital 60",
  start_date: "2020-09-16",
  expiry_date: nil,
},{
  name: "Andrew Parsons",
  email: "andrewparsons@gov.nl.ca",
  subscription_type: "Annual Digital 60",
  start_date: "2021-09-14",
  expiry_date: nil,
},{
  name: "shawn.lillington @bellaliant.net",
  email: "shawn.lillington@bellaliant.net",
  subscription_type: "Annual Digital 60",
  start_date: "2021-09-02",
  expiry_date: nil,
  },{
    name: "tskinner2002@hotmail.com",
    email: "tskinner2002@hotmail.com",
    subscription_type: "Annual Digital 60",
    start_date: "2021-08-31",
    expiry_date: nil,
    },{
      name: "Rosalyn Roy",
      email: "tygerlylly448@hotmail.com",
      subscription_type: "Annual Digital 60",
      start_date: "2021-08-31",
      expiry_date: nil,
      },{
        name: "Darlene Kettle",
        email: "darlenekettle@eastlink.ca",
        subscription_type: "Annual Digital 60",
        start_date: "2021-08-29",
        expiry_date: nil,
        },{
          name: "Niki Carroll",
          email: "starchild698@yahoo.ca",
          subscription_type: "Annual Digital 60",
          start_date: "2021-08-27",
          expiry_date: nil,
          },{
           name: "twosmond@gmail.com",
           email: "twosmond@gmail.com",
           subscription_type: "Annual Digital 60",
           start_date: "2021-08-26",
           expiry_date: nil,
                   },
          ]
#         {
#           name: "",
# email: "",
# subscription_type: "",
# start_date: "",
# expiry_date: "",
# },{
# name: "",
# email: "",
# subscription_type: "",
# start_date: "",
# expiry_date: "",
# },{
# name: "",
# email: "",
# subscription_type: "",
# start_date: "",
# expiry_date: "",
# },{
# name: "",
# email: "",
# subscription_type: "",
# start_date: "",
# expiry_date: "",
# }